import React from "react";
import RegisterView from "@/components/views/auth/Register";
import { Poppins } from "next/font/google";
import Head from "next/head";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const RegisterPage = () => {
  return (
    <>
      <Head>
        <title>Register Account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <RegisterView />
    </>
  );
};

export default RegisterPage;
