import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { getSession, signOut, useSession } from "next-auth/react";
import { GetServerSideProps } from "next";
import { useEffect } from "react";
import { saveToLocalStorage } from "@/services/auth";

export default function Home() {
  const { data: session } = useSession();
  useEffect(() => {
    if (session) {
      saveToLocalStorage(session);
    }
  }, [session]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello world</h1>
      <p>{session?.user?.email}</p>
      <button onClick={() => signOut()}>Sign Out</button>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);
  console.log(session);
  if (!session) {
    return {
      redirect: {
        destination: "/auth/register",
        permanent: false,
      },
    };
  }

  return {
    props: { session }, // Pastikan session diteruskan sebagai properti ke komponen Home
  };
};
