import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { getSession, signOut, useSession } from "next-auth/react";
import { GetServerSideProps } from "next";
import { Session } from "next-auth";
import { useEffect } from "react";

export default function Home() {
  const { data: session } = useSession();
  console.log(session);

  useEffect(() => {
    console.log("session index page", session);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      {session && Object.keys(session).length > 0 && (
        <>
          <Head>
            <title>Home</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <h1>Hello world</h1>
          <p>{session.user?.email}</p>
          <button onClick={() => signOut()}>Sign Out</button>
        </>
      )}
    </>
  );
}
