import React from "react";
import DashboardAdmin from "@/components/views/admin/Dashboard";
import Head from "next/head";

const AdminPage = () => {
  return (
    <>
      <Head>
        <title>Admin Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardAdmin />
    </>
  );
};

export default AdminPage;
